### ISSUE TITLE
varlet-cli 创建项目报错

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#206]
# Bug report 🐞
执行varlet-cli gen verlet-cli-test，创建项目报错，错误信息如下：
C:\Users\xxx\AppData\Local\Yarn\Data\global\node_modules\@varlet\markdown-vite-plugin\index.js:27
    const partComponents = partImports?.map((importer) => {
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\seaton\AppData\Local\Yarn\Data\global\node_modules\@varlet\cli\lib\config\vite.config.js:19:46)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
## Version & Environment
node:12.18.3

**Comment by haoziqaq** [comment]
node版本低了，升级到最新版本
