### ISSUE TITLE
朋友varlet这么项目是怎么跑的，我看用的是lerna的架构？

### ISSUE THREAD

**Issue by zzh3319** [haoziqaq/varlet#6]
全局安装了sudo npm install @varlet/cli -g         然后代在varlet-ui路径李 npm run dev 还是跑不起来  留个联系方式呗，想聊聊这个ui库
$ npm run dev                    

> @varlet/ui@1.0.1 dev /Users/zhongzhenhua/Downloads/varlet-dev 2/packages/varlet-ui
> varlet-cli dev

internal/fs/utils.js:307
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/@varlet/cli/site/site.config.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at getVarletConfig (/usr/local/lib/node_modules/@varlet/cli/lib/config/varlet.config.js:10:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@varlet/cli/lib/config/varlet.config.js:14:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/@varlet/cli/site/site.config.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @varlet/ui@1.0.1 dev: `varlet-cli dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @varlet/ui@1.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhongzhenhua/.npm/_logs/2021-04-25T10_18_01_730Z-debug.log

**Comment by haoziqaq** [comment]
qq 357229046------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月25日(星期天) 晚上6:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[haoziqaq/varlet] 朋友varlet这么项目是怎么跑的，我看用的是lerna的架构？ (#6)

**Comment by haoziqaq** [comment]
首先确保你安装了yarn, 在根目录下yarn bootstrap依赖建立完毕之后在varlet-ui下yarn dev

**Comment by haoziqaq** [comment]
接下来不久我们会更新开发指南

**Comment by haoziqaq** [comment]
开发指南已更新

**Comment by haoziqaq** [comment]
群号1035119557



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月25日(周日) 晚上6:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [haoziqaq/varlet] 朋友varlet这么项目是怎么跑的，我看用的是lerna的架构？ (#6)




 
全局安装了sudo npm install @varlet/cli -g         然后代在varlet-ui路径李 npm run dev 还是跑不起来  留个联系方式呗，想聊聊这个ui库
 $ npm run dev
  
@***@***.*** dev /Users/zhongzhenhua/Downloads/varlet-dev 2/packages/varlet-ui
 varlet-cli dev
  
internal/fs/utils.js:307
 throw err;
 ^
 
Error: EACCES: permission denied, open ***@***.***/cli/site/site.config.json'
 at Object.openSync (fs.js:476:3)
 at Object.writeFileSync (fs.js:1467:35)
 at getVarletConfig ***@***.***/cli/lib/config/varlet.config.js:10:16)
 at Object. ***@***.***/cli/lib/config/varlet.config.js:14:24)
 at Module._compile (internal/modules/cjs/loader.js:1063:30)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
 at Module.load (internal/modules/cjs/loader.js:928:32)
 at Function.Module._load (internal/modules/cjs/loader.js:769:14)
 at Module.require (internal/modules/cjs/loader.js:952:19)
 at require (internal/modules/cjs/helpers.js:88:18) {
 errno: -13,
 syscall: 'open',
 code: 'EACCES',
 path: ***@***.***/cli/site/site.config.json'
 }
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! @***@***.*** dev: varlet-cli dev
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the @***@***.*** dev script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
 npm ERR!     /Users/zhongzhenhua/.npm/_logs/2021-04-25T10_18_01_730Z-debug.log
